In [1]:
import numpy as np

In [2]:
# matrix 
my_matrix = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print('The item is {matrix}, and its type is {type}'.format(type=type(my_matrix), matrix=my_matrix))

The item is [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], and its type is <class 'numpy.ndarray'>


In [5]:
# zeros/ones
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# linspace vs. arange 
print('linespace takes begin, end(included) and # of evenly space item like {linspacesample}'.format(linspacesample=np.linspace(0,10,11))
      +' while arange takes begin, end(not included) and gap value like {arangesample}'.format(arangesample=np.arange(0, 10, 1)))

linespace takes begin, end(included) and # of evenly space item like [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] while arange takes begin, end(not included) and gap value like [0 1 2 3 4 5 6 7 8 9]


In [19]:
# identify matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# random numbers [0,1) 
np.random.seed(42)

## 1. uniform distribution 
print('uniform distirbution{sample}'.format(sample=np.random.rand(5,2)))

## 2. normal distribution 
print('normal distirbution{sample}'.format(sample=np.random.randn(5,2)))

## 3. integers 
print('uniform dist integers{sample}'.format(sample=np.random.randint(0, 10, (5,2))))

uniform distirbution[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]
 [0.05808361 0.86617615]
 [0.60111501 0.70807258]]
normal distirbution[[-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024]
 [-1.72491783 -0.56228753]
 [-1.01283112  0.31424733]]
uniform dist integers[[2 6]
 [3 8]
 [2 4]
 [2 6]
 [4 8]]


In [26]:
# reshape
arr = np.array([1,2,3,4,5,6,7,8])
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# find max/min value/index 
print('max value is {maxv} and location is {loc}'.format(maxv=arr.max(), loc=arr.argmax()))

max value is 8 and location is 7


In [31]:
# type 
print(type(arr))
print(arr.dtype)
print(arr.shape)

<class 'numpy.ndarray'>
int64
(8,)


In [33]:
# broadcasting (change in place, always use .copy() if don't want to change original array)
arr = np.arange(0, 10)
print(arr)
arr[0:3] = 100
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[100 100 100   3   4   5   6   7   8   9]


In [4]:
# map & lambda function 
"""
lambda arguments: expression
map(function, iterable)
"""
maxi = lambda x, y: x if x > y else y 
print(maxi(4, 6))
squares = list(map(lambda n: n**2, range(1,10,2)))
print(squares)

6
[1, 9, 25, 49, 81]


In [ ]:
# list comprehension 
